# $Id: Makefile,v 1.1 1996/06/06 03:33:22 tim Exp $

pkg_topdir=../../..

include $(pkg_topdir)/mk/top.mk

PROGRAM = t_stack

SRCS = t_stack.c
OBJS = $(SRCS:c=o)
DOCS = $(SRCS:c=txt)

include $(pkg_mkdir)/bin.mk
include $(pkg_mkdir)/doc.mk


