# $Id: Makefile,v 1.3 1996/06/06 03:27:15 tim Exp $
#

pkg_topdir=../../..

include $(pkg_topdir)/mk/top.mk

PROGRAM = abcde

SRCS = abcde.c
OBJS = $(SRCS:c=o)
DOCS = abcde.txt

include $(pkg_mkdir)/bin.mk
include $(pkg_mkdir)/doc.mk

