# Copyright © 2013 Rutger F.H. Hofman. All Rights Reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 
# 3. The name of the author may not be used to endorse or promote products
# derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY [LICENSOR] "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

LIB	= ../libniffparser.a

SRC	=
SRC	+= Accidental.c
SRC	+= AltEndingGraphic.c
SRC	+= Arpeggio.c
SRC	+= Articulation.c
SRC	+= AugDot.c
SRC	+= Barline.c
SRC	+= Beam.c
SRC	+= ChnkLenTable.c
SRC	+= ChordSymbol.c
SRC	+= Chunk.c
SRC	+= Clef.c
SRC	+= CustomGraphicChk.c
SRC	+= DefaultValues.c
SRC	+= Dynamic.c
SRC	+= EpsGraphic.c
SRC	+= FiguredBass.c
SRC	+= Fingering.c
SRC	+= FontDescription.c
SRC	+= FontSymbol.c
SRC	+= Glissando.c
SRC	+= GuitarGrid.c
SRC	+= GuitarTabNum.c
SRC	+= Hairpin.c
SRC	+= HarpPedal.c
SRC	+= KeySignNonstandard.c
SRC	+= KeySignature.c
SRC	+= Line.c
SRC	+= Lyric.c
SRC	+= MeasureNumbering.c
SRC	+= MidiDataStream.c
SRC	+= NiffInfo.c
SRC	+= Notehead.c
SRC	+= OctaveSign.c
SRC	+= Ornament.c
SRC	+= PageHeader.c
SRC	+= Parenthesis.c
SRC	+= Part.c
SRC	+= PedalOrgan.c
SRC	+= PedalPiano.c
SRC	+= Portamento.c
SRC	+= PsType1Font.c
SRC	+= PsType3Font.c
SRC	+= RehearsalMark.c
SRC	+= RepeatSign.c
SRC	+= Rest.c
SRC	+= Slur.c
SRC	+= StaffGrouping.c
SRC	+= StaffHeader.c
SRC	+= Stem.c
SRC	+= StringTable.c
SRC	+= SystemHeader.c
SRC	+= SystemSeparation.c
SRC	+= TagActivate.c
SRC	+= TagInactivate.c
SRC	+= TempoMarkNonstandard.c
SRC	+= TempoMarking.c
SRC	+= Text.c
SRC	+= Tie.c
SRC	+= TimeSigNonstandard.c
SRC	+= TimeSignature.c
SRC	+= TimeSlice.c
SRC	+= Tremolo.c
SRC	+= Tuplet.c

include ../../common.mk

