.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
.ds L' '
.ds R' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds L' `
.ds R' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH inherit 3 "niffio" "14/Jun/96" "NIFFIO Documentation"
.IX Title "inherit 3"
.UC
.IX Name "inherit - RIFFIO-style file operations on NIFFIOFiles"
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
.IX Header "NAME"
inherit \- RIFFIO\-style file operations on NIFFIOFiles
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
All of these routines behave just like their RIFFIO counterparts.
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOFileGetFormType()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIORead()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOWrite()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOSeek()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOTell()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOChunkCreate()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOChunkFinalize()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOChunkDescend()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOChunkAscend()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOChunkDataSeek()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOChunkDataEnd()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOChunkEnd()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOWrite8()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOWrite16()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOWrite32()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOWriteFOURCC()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIORead8()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIORead16()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIORead32()\fR
.Ip "\(bu" 4
.IX Item "\(bu"
\fINIFFIOReadFOURCC()\fR
.SH "NIFFIOFileGetFormType"
.IX Header "NIFFIOFileGetFormType"
See \fIRIFFIOFileGetFormType()\fR
.PP
.Vb 2
\&     RIFFIOFormType
\&     NIFFIOFileGetFormType(NIFFIOFile *pnf)
.Ve
.SH "NIFFIORead"
.IX Header "NIFFIORead"
See \fIRIFFIORead()\fR
.PP
.Vb 2
\&     long
\&     NIFFIORead(NIFFIOFile *pnf, void *bufferp, long n)
.Ve
.SH "NIFFIOWrite"
.IX Header "NIFFIOWrite"
See \fIRIFFIOWrite()\fR
.PP
.Vb 2
\&     long
\&     NIFFIOWrite(NIFFIOFile *pnf, void *bufferp, long n)
.Ve
.SH "NIFFIOSeek"
.IX Header "NIFFIOSeek"
See \fIRIFFIOSeek()\fR
.PP
.Vb 2
\&     RIFFIOSuccess
\&     NIFFIOSeek(NIFFIOFile *pnf, RIFFIOOffset offset, RIFFIOSeekOrigin origin)
.Ve
.SH "NIFFIOTell"
.IX Header "NIFFIOTell"
See \fIRIFFIOTell()\fR
.PP
.Vb 2
\&     long
\&     NIFFIOTell(NIFFIOFile *pnf)
.Ve
.SH "NIFFIOChunkCreate"
.IX Header "NIFFIOChunkCreate"
See \fIRIFFIOChunkCreate()\fR
.PP
.Vb 2
\&     RIFFIOSuccess
\&     NIFFIOChunkCreate(NIFFIOFile *pnf, RIFFIOChunk *pchunk)
.Ve
.SH "NIFFIOChunkFinalize"
.IX Header "NIFFIOChunkFinalize"
See \fIRIFFIOChunkFinalize()\fR
.PP
.Vb 2
\&     RIFFIOSuccess
\&     NIFFIOChunkFinalize(NIFFIOFile *pnf, RIFFIOChunk *pchunk)
.Ve
.SH "NIFFIOChunkAscend"
.IX Header "NIFFIOChunkAscend"
See \fIRIFFIOChunkAscend()\fR
.PP
.Vb 2
\&     RIFFIOSuccess
\&     NIFFIOChunkAscend(NIFFIOFile *pnf, RIFFIOChunk *pchunk)
.Ve
.SH "NIFFIOChunkDescend"
.IX Header "NIFFIOChunkDescend"
See \fIRIFFIOChunkDescend()\fR
.PP
.Vb 2
\&     RIFFIOSuccess
\&     NIFFIOChunkDescend(NIFFIOFile *pnf, RIFFIOChunk *pchunk)
.Ve
.SH "NIFFIOChunkDataSeek"
.IX Header "NIFFIOChunkDataSeek"
See \fIRIFFIOChunkDataSeek()\fR
.PP
.Vb 2
\&     RIFFIOSuccess
\&     NIFFIOChunkSeekData(NIFFIOFile *pnf, const RIFFIOChunk *pchunk)
.Ve
.SH "NIFFIOChunkDataEnd"
.IX Header "NIFFIOChunkDataEnd"
See \fIRIFFIOChunkDataEnd()\fR
.PP
.Vb 2
\&     int
\&     NIFFIOChunkDataEnd(NIFFIOFile *pnf, RIFFIOChunk *pchunk)
.Ve
.SH "NIFFIOChunkEnd"
.IX Header "NIFFIOChunkEnd"
See \fIRIFFIOChunkEnd()\fR
.PP
.Vb 2
\&     int
\&     NIFFIOChunkEnd(NIFFIOFile *pnf, RIFFIOChunk *pchunk)
.Ve
.SH "NIFFIOWrite8"
.IX Header "NIFFIOWrite8"
See \fIRIFFIOWrite8()\fR
.PP
.Vb 1
\&     RIFFIOSuccess NIFFIOWrite8(NIFFIOFile *pnf, unsigned char uc)
.Ve
.SH "NIFFIOWrite16"
.IX Header "NIFFIOWrite16"
See \fIRIFFIOWrite16()\fR
.PP
.Vb 1
\&     RIFFIOSuccess NIFFIOWrite16(NIFFIOFile *pnf, unsigned short us)
.Ve
.SH "NIFFIOWrite32"
.IX Header "NIFFIOWrite32"
See \fIRIFFIOWrite32()\fR
.PP
.Vb 1
\&     RIFFIOSuccess NIFFIOWrite32(NIFFIOFile *pnf, unsigned long ul)
.Ve
.SH "NIFFIOWriteFOURCC"
.IX Header "NIFFIOWriteFOURCC"
See \fIRIFFIOWriteFOURCC()\fR
.PP
.Vb 1
\&     RIFFIOSuccess NIFFIOWriteFOURCC(NIFFIOFile *pnf, FOURCC fcc)
.Ve
.SH "NIFFIORead8"
.IX Header "NIFFIORead8"
See \fIRIFFIORead8()\fR
.PP
.Vb 1
\&     RIFFIOSuccess NIFFIORead8(NIFFIOFile *pnf, unsigned char *puc)
.Ve
.SH "NIFFIORead16"
.IX Header "NIFFIORead16"
See \fIRIFFIORead16()\fR
.PP
.Vb 1
\&     RIFFIOSuccess NIFFIORead16(NIFFIOFile *pnf, unsigned short *pus)
.Ve
.SH "NIFFIORead32"
.IX Header "NIFFIORead32"
See \fIRIFFIORead32()\fR
.PP
.Vb 1
\&     RIFFIOSuccess NIFFIORead32(NIFFIOFile *pnf, unsigned long *pul)
.Ve
.SH "NIFFIOReadFOURCC"
.IX Header "NIFFIOReadFOURCC"
See \fIRIFFIOReadFOURCC()\fR
.PP
.Vb 1
\&     RIFFIOSuccess NIFFIOReadFOURCC(NIFFIOFile *pnf, FOURCC *pfcc)
.Ve

.rn }` ''
