# $Id: Makefile,v 1.1 1996/06/06 03:33:42 tim Exp $

pkg_topdir=../../..

include $(pkg_topdir)/mk/top.mk

PROGRAM = t_fcc

SRCS = t_fcc.c
OBJS = $(SRCS:c=o)
DOCS = t_fcc.txt

include $(pkg_mkdir)/bin.mk
include $(pkg_mkdir)/doc.mk
