# $Id: Makefile,v 1.2 1996/06/06 06:08:23 tim Exp $
#
# 
pkg_topdir=..

include $(pkg_topdir)/mk/top.mk

check::
	check

clean::
	rm -f *.dif
	rm -f *.out
	rm -f *.core
	rm -f *.data
	rm -f *.rif

distclean:: clean

doc::

