
=head1 NAME

fcc - Four-character code operations

=head1 SYNOPSIS

=over 4

=item *

RIFFIOFOURCCIsValid()

=item *

RIFFIOFOURCCToString()

=back

=head1 RIFFIOFOURCCIsValid

Check the validity of a four-character code.

     int
     RIFFIOFOURCCIsValid(RIFFIOFOURCC fcc)


Check <fcc> according to the rules

=over 4

=item *

alphanumeric ASCII characters only [A-Z],[0-9],[a-z]

=item *

padded on the right with spaces

=item *

no embedded spaces

=back

=head2 RETURN

1 - if fcc is valid,

0 - otherwise

=head2 BUGS

This does not work on FOURCC's that require escape codes to
represent them in string form.

=head1 RIFFIOFOURCCToString

Write a four-character code into a string.

     void
     RIFFIOFOURCCToString(const RIFFIOFOURCC fcc, char *str)


=head2 ENTRY

T <*str> must already be allocated to hold at
least RIFFIO_FOURCC_MIN characters.

=head2 EXIT

Writes the four characters (possibly using escape sequences)
of <fcc> and a terminating NUL into <*str>.

=head2 BUGS

This does not work for FOURCC's that require escape codes to
represent them as a string.
