# $Id: Makefile,v 1.3 1996/06/06 03:34:05 tim Exp $

pkg_topdir=../../..

include $(pkg_topdir)/mk/top.mk

EXPORT_PROGRAM = riffdump

SRCS = riffdump.c
OBJS = $(SRCS:c=o)
DOCS = riffdump.txt

include $(pkg_mkdir)/bin.mk
include $(pkg_mkdir)/doc.mk

