# $Id: Makefile,v 1.1 1996/06/06 05:18:32 tim Exp $

pkg_topdir=../../..

include $(pkg_topdir)/mk/top.mk

EXPORT_PROGRAM = nif001

SRCS = nif001.c

OBJS = $(SRCS:c=o)
DOCS = $(SRCS:c=txt)
include $(pkg_mkdir)/bin.mk
include $(pkg_mkdir)/doc.mk

