# Copyright © 2013 Rutger F.H. Hofman. All Rights Reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 
# 3. The name of the author may not be used to endorse or promote products
# derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY [LICENSOR] "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

LIB	= ../libniffparser.a

SRC	=
SRC	+= AbsPlacement.c
SRC	+= AltEnding.c
SRC	+= AnchorOverride.c
SRC	+= ArticDirection.c
SRC	+= BezierIncoming.c
SRC	+= BezierOutgoing.c
SRC	+= ChordSymbolsOffset.c
SRC	+= CustomFontChar.c
SRC	+= CustomGraphicTag.c
SRC	+= EndOfSystem.c
SRC	+= FannedBeam.c
SRC	+= FigBassOffset.c
SRC	+= FontID.c
SRC	+= GraceNote.c
SRC	+= GuitarGridOffset.c
SRC	+= GuitarTabTag.c
SRC	+= Height.c
SRC	+= ID.c
SRC	+= Invisible.c
SRC	+= LargeSize.c
SRC	+= LineQuality.c
SRC	+= LogicalPlacement.c
SRC	+= LyricVerseOffset.c
SRC	+= MidiPerformance.c
SRC	+= MultiNodeEndOfSyst.c
SRC	+= MultiNodeStartOfSyst.c
SRC	+= NumStaffLines.c
SRC	+= NumberOfFlags.c
SRC	+= NumberOfNodes.c
SRC	+= NumberStyle.c
SRC	+= Ossia.c
SRC	+= PartDescOverride.c
SRC	+= PartID.c
SRC	+= RefPtOverride.c
SRC	+= RehearsalOffset.c
SRC	+= RestNumeral.c
SRC	+= Silent.c
SRC	+= SlashedStem.c
SRC	+= SmallSize.c
SRC	+= SpacingByPart.c
SRC	+= SplitStem.c
SRC	+= StaffName.c
SRC	+= StaffStep.c
SRC	+= Tag.c
SRC	+= Thickness.c
SRC	+= TieDirection.c
SRC	+= TupletDesc.c
SRC	+= VoiceID.c
SRC	+= Width.c

include ../../common.mk

